import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import json

# --- Load Dummy Data ---
with open("dummy_data.json", "r") as f:
    data = json.load(f)

# Convert to DataFrames
products_df = pd.DataFrame(data["products"])
customers_df = pd.DataFrame([
    {"Segment": "New Customers", "Number of Customers": data["customers"]["new_customers"]},
    {"Segment": "Returning Customers", "Number of Customers": data["customers"]["returning_customers"]}
])

# --- Streamlit Layout ---
st.set_page_config(page_title="AI eCommerce Dashboard", layout="wide")
st.title("📊 AI-Powered eCommerce Dashboard (Demo)")
st.subheader("Client Store Analytics & Recommendations (Dummy Data)")

# --- KPI Metrics ---
total_revenue = products_df["revenue"].sum()
total_units = products_df["units_sold"].sum()
new_customers = customers_df.loc[customers_df['Segment']=='New Customers', 'Number of Customers'].values[0]
returning_customers = customers_df.loc[customers_df['Segment']=='Returning Customers', 'Number of Customers'].values[0]

col1, col2, col3, col4 = st.columns(4)
col1.metric("💰 Total Revenue ($)", f"{total_revenue}")
col2.metric("📦 Total Units Sold", f"{total_units}")
col3.metric("🆕 New Customers", f"{new_customers}")
col4.metric("👥 Returning Customers", f"{returning_customers}")

st.markdown("---")

# --- Product Sales Bar Chart ---
st.subheader("Top Selling Products")
fig, ax = plt.subplots()
ax.bar(products_df["title"], products_df["units_sold"], color='skyblue')
ax.set_xlabel("Products")
ax.set_ylabel("Units Sold")
ax.set_title("Units Sold per Product")
st.pyplot(fig)

# --- Product Revenue Pie Chart ---
st.subheader("Revenue Distribution")
fig2, ax2 = plt.subplots()
ax2.pie(products_df["revenue"], labels=products_df["title"], autopct='%1.1f%%', startangle=90)
ax2.set_title("Revenue Share by Product")
st.pyplot(fig2)

st.markdown("---")

# --- Product Insights Table ---
st.subheader("AI Product Insights (Generated by Gemini / Dummy Suggestions)")
st.dataframe(products_df[["title","category","revenue"]])

# --- Customer Insights Table ---
st.subheader("AI Customer Insights (Dummy Suggestions)")
st.dataframe(customers_df)

st.markdown("---")
st.info("✅ This dashboard is running with dummy data. Once Shopify API is connected, it will show real store insights automatically.")
